### ISSUE TITLE
2014 Primary Kern test failure

### ISSUE THREAD

**Issue by charles-difazio** [openelections/openelections-data-ca#106]
Missing write-in candidates.  Precinct-level results available in [Statement of Votes Cast](https://elections.co.kern.ca.us/elections/SOVC/SOVC_June_3_2014_full.pdf)

```
E           AssertionError: Kern failed
E           assert {('"Bo" Bogda...): 12435, ...} == {('"Bo" Bogdan...): 12435, ...}
E             Omitting 83 identical items, use -v to show
E             Left contains more items:
E             {('Gail K. Lightfoot', 'Kern', 23.0, 'U.S. House'): 28,
E              ('Mike Biglay', 'Kern', 23.0, 'U.S. House'): 154,
E              ('Nickolas Wildstar', 'Kern', '', 'Governor'): 1,
E              ('Raul Garcia', 'Kern', 23.0, 'U.S. House'): 296,
E              ('Ronald L. Porter', 'Kern', 23.0, 'U.S. House'): 36,
E              ('Ruth Musser-Lopez', 'Kern', 16.0, 'State Senate'): 87}
E             Use -v to get the full diff
```

**Comment by carbonphyber** [comment]
Fixed in #151 

Note: that link is 404. [Statement of Votes Cast on Archive.org](https://web.archive.org/web/20160605145259/https://elections.co.kern.ca.us/elections/SOVC/SOVC_June_3_2014_full.pdf)

**Comment by warwickmm** [comment]
I believe this can be closed.  @dwillis, it looks like I have permissions to close issues.  Would you be OK with me closing some of these, or would you prefer I comment on them for you to act on?

**Comment by dwillis** [comment]
@warwickmm go for it!
