### ISSUE TITLE
Convert 2020 General Election Precinct Results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ca#144]
If you want to work on a county, add a comment saying which one you'd like to work on or email openelections@gmail.com. You can either email us finished CSV files or submit a pull request, whatever is easiest. 

The results files you'll be converting are in the [California sources repository](https://github.com/openelections/openelections-sources-ca/tree/master/2020). Many of these are either PDFs or Excel files. For electronic PDFs, we recommend using [Tabula](http://tabula.technology/), which is free, to extract data. The goal is to create a single CSV file for each county, with the following headers:

`county`, `precinct`, `office`, `district`, `party`, `candidate`, `votes`

If the county file also provides a breakdown of votes by method, include those using the following headers:

`early_voting`, `election_day`, `provisional`, `mail`

For the following offices: President, U.S. House, and any State Senate or State Assembly races. File names should be: `20201103__ca__general__{county_name}__precinct.csv`, with the county name lower case and spaces replaced with underscores.

An example file [looks like this](https://github.com/openelections/openelections-data-ca/blob/master/2020/20201103__ca__general__marin__precinct.csv)

- [x]  Alameda
- [x]  Alpine
- [x]  Amador
- [x]  Butte
- [x]  Calaveras
- [x]  Colusa
- [x]  Contra Costa
- [x]  Del Norte
- [x]  El Dorado
- [x]  Fresno
- [x]  Glenn
- [x]  Humboldt
- [x]  Imperial
- [x]  Inyo
- [x]  Kern
- [x]  Kings
- [x]  Lake
- [x]  Lassen
- [x]  Los Angeles
- [x]  Madera
- [x]  Marin
- [x]  Mariposa
- [x]  Mendocino
- [x]  Merced
- [x]  Modoc
- [x]  Mono
- [x]  Monterey
- [x]  Napa
- [x]  Nevada
- [x]  Orange
- [x]  Placer
- [x]  Plumas
- [x]  Riverside
- [x]  Sacramento
- [x]  San Benito
- [x]  San Bernardino
- [x]  San Diego
- [x]  San Francisco
- [x]  San Joaquin
- [x]  San Luis Obispo
- [x]  San Mateo
- [x]  Santa Barbara
- [x]  Santa Clara
- [x]  Santa Cruz
- [x]  Shasta
- [x]  Sierra
- [x]  Siskiyou
- [x]  Solano
- [x]  Sonoma
- [x]  Stanislaus
- [x]  Sutter
- [x]  Tehama
- [x]  Trinity
- [x]  Tulare
- [x]  Tuolumne
- [x]  Ventura
- [x]  Yolo
- [x]  Yuba

**Comment by aidanconnolly** [comment]
I'll start on Alameda.

**Comment by andysylvester** [comment]
I will take Alpine County.

**Comment by goodasha** [comment]
Added Lake general #147.

**Comment by goodasha** [comment]
I will take Mendocino.

**Comment by aidanconnolly** [comment]
I've got Placer.

**Comment by carbonphyber** [comment]
I took a stab at Santa Clara #148 .
If any other counties use ClarityElections.com to store/display elections data, please have a look at my PR.

**Comment by goodasha** [comment]
I will take Tulare.

**Comment by omarcoming** [comment]
I will take Colusa

**Comment by omarcoming** [comment]
How should we deal with precincts where vote tallies have been withheld by the Elections Dept due to the small precinct / low turnout resulting in issues with protecting voter privacy? 

For example, Contra Costa county has several precincts where the In-Person tallies are censored but we could easily infer the proper counts by subtracting the Vote By Mail portion from the Total. Should I be including that inferred data? 

The other issue I'm running in to is with precincts that haven't reported either the Vote By Mail or In-Person tallies for any candidates and only include the totals. What is the standard for representing missing data on this project?

**Comment by dwillis** [comment]
@omarcoming good questions, thank you! We don't infer data, so try to represent things as they are reported. In practice, you can put `N/A` in the appropriate column for tallies that are withheld. For precincts that only have the totals, just list the total.

**Comment by omarcoming** [comment]
> If the county file also provides a breakdown of votes by method, include those using the following headers:
> 
> early_voting, election_day, provisional, mail

What if the breakdown is just in-person vs mail?

**Comment by dwillis** [comment]
@omarcoming then just use `mail` and `election_day`, unless the in-person combines election day and early voting. In that case, do `mail` and `in_person` and we'll figure it out.

**Comment by goodasha** [comment]
I'll take Imperial

**Comment by carbonphyber** [comment]
I'll work on Madera.

**Comment by dwillis** [comment]
Hi @carbonphyber - I should have marked it, but someone else claimed Madera this week.

**Comment by carbonphyber** [comment]
> Hi @carbonphyber - I should have marked it, but someone else claimed Madera this week. Any chance you would entertain another?

I've already submitted a PR for it.

I'll work on Riverside next

**Comment by carbonphyber** [comment]
I'll work on Santa Barbara

**Comment by carbonphyber** [comment]
I'm going to try Los Angeles. Hopefully it doesn't take too long.

**Comment by goodasha** [comment]
> I'll take Imperial

This file has Absentee in addition to early voting, vote by mail and election day. How is absentee handled?

**Comment by dwillis** [comment]
> > I'll take Imperial
> 
> 
> 
> This file has Absentee in addition to early voting, vote by mail and election day. How is absentee handled?

Just add another column called absentee.

**Comment by goodasha** [comment]
I can take Tehama.

**Comment by goodasha** [comment]
I can give Contra Costa a try

**Comment by dwillis** [comment]
@goodasha that would be fabulous, thank you!

**Comment by goodasha** [comment]
I can take San Bernardino

**Comment by dwillis** [comment]
@goodasha thank you!

**Comment by goodasha** [comment]
> @goodasha thank you!

Question: This file has Designated Mail Ballot in addition to Mail Ballot as a type of vote - how should that be labeled? And are Provisional votes labeled provisional in the final file?

**Comment by dwillis** [comment]
You can label it as designated_mail, and please do include provisional votes with the label 'provisional'

**Comment by goodasha** [comment]
I can take Kern

**Comment by goodasha** [comment]
I can take Kern.

**Comment by goodasha** [comment]
Feeling a little rusty on this. Does 'Mail Ballot' translate to 'mail', and 'Vote by Mail' map to ? 'absentee'?

**Comment by dwillis** [comment]
@goodasha `Mail Ballot` would be `early_voting` in this case, and `Vote by Mail` would be just `mail`. Thanks!
