### ISSUE TITLE
Some reorganizing

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ca#19]
@charles-difazio: thank you again for all the work you've done with California results. I'm going to be doing a little reorganizing of some of the files - mostly combining multiple county precinct files into a single one. Just wanted to give you a heads-up, it shouldn't impact anything you're doing.

**Comment by charles-difazio** [comment]
Thanks for the heads-up and the cleanup.

Is there a standard place people coordinate work for the project? Like with the headers cleanup, I wouldn't want to do work anyone else already has covered.

**Comment by dwillis** [comment]
Not really, no - that's a good point. In this case I probably should have waited until you were finished to do this kind of thing. But once I started, I should have given better updates of what I was doing here.

**Comment by charles-difazio** [comment]
Not a big deal. I'll start making more use of the issue tracker to keep track of what's in progress and what needs to be done.
