### ISSUE TITLE
Data Validation

### ISSUE THREAD

**Issue by charles-difazio** [openelections/openelections-data-ca#21]
We should perform some data validation ensuring certain basic features of the data. Possibilities include:
- county-level vote counts == sum(precinct-level vote counts)
- state-level vote counts == sum(county-level vote counts)
- each precinct file contains a single county
- number of counties is correct

There are probably more, but these would make a good start.  Has this been implemented for any of the other states?

**Comment by dwillis** [comment]
Our [data processing pipeline](http://docs.openelections.net/guide/) envisions a validation step after raw results are standardized. We've been focused on loading and publishing raw results, so I don't believe validations have been implemented for any of the other states yet. But would be interested in seeing how it might be approached at this stage.

**Comment by charles-difazio** [comment]
Closing this one out, we can just use a label for further features as desired.
