### ISSUE TITLE
Los Angeles County 2016 Precinct Fails Validation

### ISSUE THREAD

**Issue by charles-difazio** [openelections/openelections-data-ca#56]
President and U.S. Senate don't match.

**Comment by charles-difazio** [comment]
On the [Statement of Vote](http://www.lavote.net/documents/SVC/3496_SVC_Precinct_ZBC.pdf), there's Precinct Total, VBM Total, and Group Total.  The first two seem to be accounted for, but the last one isn't.  @dwillis any idea what that is?  It has precincts associated with it, but I'm going to initially just put the totals in to get the tests to pass.

**Comment by dwillis** [comment]
That's a new one for me. @joemfox?

**Comment by charles-difazio** [comment]
Looks like this is referenced in the [Problems](https://github.com/datadesk/california-2016-election-precinct-maps#problems) section upstream.

"Some counties have results that couldn't be combined with a geographic region. There aren't many, but they do exist (Los Angeles County is one)."

#59 is start to fix this, we can expand them out in further changes.

**Comment by joemfox** [comment]
Sorry, I just saw this thread. LA County has some ballots that aren't assigned to actual precincts. They are put into "precincts" called "ballot groups" but they don't have a geographic component and cannot be assigned to any, according to the county. More work could be done to define exactly what ballots go into these groups; I'm not totally clear on that.

**Comment by lephead** [comment]
One of the things I do is find a municipal election and look at the bottom of it and you will find the ballot groups for that city.
